version: 2
updates:
  - package-ecosystem: github-actions
    directory: .github/workflows
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(deps): update GitHub Actions workflows"
    labels:
      - github-actions