name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TERMINUS_ENV: ci-${{ github.run_number }}
      TERMINUS_SITE: plague-music-canary
      WORDPRESS_ADMIN_USERNAME: pantheon
      WORDPRESS_ADMIN_PASSWORD: ${{ secrets.WORDPRESS_ADMIN_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Terminus
        uses: pantheon-systems/terminus-github-actions@main
        with:
          pantheon-machine-token: ${{ secrets.TERMINUS_TOKEN }}

      - name: Set up environment variables
        run: |
          echo "Test site is ${{ env.TERMINUS_SITE }}.${{ env.TERMINUS_ENV }}"
          echo "Logging in with a machine token:"
          terminus auth:login -n --machine-token="${{ secrets.TERMINUS_TOKEN }}"
          terminus whoami
          touch $HOME/.ssh/config
          echo "StrictHostKeyChecking no" >> "$HOME/.ssh/config"
          git config --global user.email "robot@dev.null"
          git config --global user.name "GitHub Actions"
          git config --global core.fileMode false

      - name: Prepare
        env:
          BRANCH_NAME: ${{ github.head_ref }}
        run: ${{ github.workspace }}/.github/bin/prepare.sh

      - name: Install & configure Behat & Mink
        run: |
          # Install Behat
          curl -L -o behat.phar https://github.com/Behat/Behat/releases/latest/download/behat.phar
          chmod +x behat.phar
          sudo mv behat.phar /usr/local/bin/behat
          
          # Install Behat Mink Extension
          mkdir -p behat-extensions && cd behat-extensions
          curl -L -o MinkExtension.phar https://github.com/Behat/MinkExtension/releases/latest/download/MinkExtension.phar
          chmod +x MinkExtension.phar
          sudo mv MinkExtension.phar /usr/local/bin/mink-extension
  
          # Install Mink & Selenium2Driver (Needed for browser testing)
          curl -L -o Mink.phar https://github.com/minkphp/Mink/releases/latest/download/Mink.phar
          chmod +x Mink.phar
          sudo mv Mink.phar /usr/local/bin/mink
  
          curl -L -o MinkSelenium2Driver.phar https://github.com/minkphp/MinkSelenium2Driver/releases/latest/download/MinkSelenium2Driver.phar
          chmod +x MinkSelenium2Driver.phar
          sudo mv MinkSelenium2Driver.phar /usr/local/bin/mink-selenium2-driver
  
          # Verify installation
          behat --version
          mink-extension --version
  

      - name: Test
        env:
          WORKSPACE_DIR: ${{ github.workspace }}
        run: ${{ github.workspace }}/.github/bin/test.sh --strict

      - name: Cleanup
        env:
          MULTIDEV_DELETE_PATTERN: ci-
        run: ${{ github.workspace }}/.github/bin/cleanup.sh
