name: Deploy to Pantheon Canary

on:
  push:
    branches:
      - main

permissions:
  contents: read
  deployments: write
  statuses: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack message (start)
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL: '#firehose'
        run: |
          MESSAGE=":rocket: **Deploying 'main' to Pantheon Canary site**"
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          MESSAGE+="\nCommit message: $COMMIT_MESSAGE"
          curl -X POST "https://slack.com/api/chat.postMessage" \
            -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{
              \"channel\": \"$SLACK_CHANNEL\",
              \"text\": \"$MESSAGE\"
            }" > /dev/null 2>&1
      - name: Deploy to Pantheon
        uses: stevector-streaming/dtp@0.2.1
        with:
          ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
          site: plague-music-canary
          machine_token: ${{ secrets.TERMINUS_TOKEN }}
      - name: Cleanup old environments
        env:
          MULTIDEV_DELETE_PATTERN: pr-
          TERMINUS_SITE: plague-music-canary
          GITHUB_REPOSITORY: ${{ github.repository }}          
        run: ${{ github.workspace }}/.github/bin/cleanup.sh
      - name: Send Slack message (finish)
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL: '#firehose'
        run: |
          MESSAGE=":white-check-mark: **Deployment complete!** :tea:"
          MESSAGE+="https://dev-plague-music-canary.pantheonsite.io"
          curl -X POST "https://slack.com/api/chat.postMessage" \
            -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{
              \"channel\": \"$SLACK_CHANNEL\",
              \"text\": \"$MESSAGE\"
            }" > /dev/null 2>&1
